/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author AKHINA BABU
 */
public class Employee extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Integer Command;

    int ADD = 0;
    int UPDATE = 1;

    /**
     * Creates new form Employee
     */
    public Employee() {
        super("Employee");
        initComponents();
        conn = dbconnect.connectdb();
        FrameInit();
    }
 private void FrameInit() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim);             ///This will let frame initialise in full screen
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new coffee.ImagePanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        txtegen = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        btnsave = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtesal = new javax.swing.JTextField();
        txtejob = new javax.swing.JTextField();
        txtephno = new javax.swing.JTextField();
        txtelname = new javax.swing.JTextField();
        txtefname = new javax.swing.JTextField();
        txteid = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        txtenteid = new javax.swing.JLabel();
        txtentefname = new javax.swing.JLabel();
        txtentelname = new javax.swing.JLabel();
        txtenteaddr = new javax.swing.JLabel();
        txtentjDateChooser1 = new javax.swing.JLabel();
        txtentegen = new javax.swing.JLabel();
        txtentephno = new javax.swing.JLabel();
        txtentjDateChooser2 = new javax.swing.JLabel();
        txtentesal = new javax.swing.JLabel();
        txtentejob = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txteaddr = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 70)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("EMPLOYEE DETAILS");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setText("PhNo");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setText("Address");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setText("Date_Of_Birth");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setText("LName");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("FName");
        jLabel3.setPreferredSize(new java.awt.Dimension(74, 28));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("EmpID");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setText("JobTitle");

        btnrefresh.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/settings.png"))); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        txtegen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtegen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        txtegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtegenActionPerformed(evt);
            }
        });
        txtegen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtegenKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel11.setText("Salary");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setText("JoinDate");

        jDateChooser1.setDateFormatString("YYYY-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyTyped(evt);
            }
        });

        jDateChooser2.setDateFormatString("YYYY-MM-dd");
        jDateChooser2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jDateChooser2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChooser2KeyTyped(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/save.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnhome.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/home.png"))); // NOI18N
        btnhome.setText("HOME");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/delete.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        txtesal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtesal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtesalActionPerformed(evt);
            }
        });
        txtesal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtesalKeyTyped(evt);
            }
        });

        txtejob.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtejob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtejobActionPerformed(evt);
            }
        });
        txtejob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtejobKeyTyped(evt);
            }
        });

        txtephno.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtephno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtephnoActionPerformed(evt);
            }
        });
        txtephno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtephnoKeyTyped(evt);
            }
        });

        txtelname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtelname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtelnameActionPerformed(evt);
            }
        });
        txtelname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtelnameKeyTyped(evt);
            }
        });

        txtefname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtefname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtefnameActionPerformed(evt);
            }
        });
        txtefname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtefnameKeyTyped(evt);
            }
        });

        txteid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txteid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteidActionPerformed(evt);
            }
        });
        txteid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txteidKeyTyped(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/add.png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/Update.png"))); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/search.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        txtenteid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtenteid.setForeground(new java.awt.Color(255, 0, 0));

        txtentefname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentefname.setForeground(new java.awt.Color(255, 0, 0));

        txtentelname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentelname.setForeground(new java.awt.Color(255, 0, 0));

        txtenteaddr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtenteaddr.setForeground(new java.awt.Color(255, 0, 0));

        txtentjDateChooser1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentjDateChooser1.setForeground(new java.awt.Color(255, 0, 0));

        txtentegen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentegen.setForeground(new java.awt.Color(255, 0, 0));

        txtentephno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentephno.setForeground(new java.awt.Color(255, 0, 0));

        txtentjDateChooser2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentjDateChooser2.setForeground(new java.awt.Color(255, 0, 0));

        txtentesal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentesal.setForeground(new java.awt.Color(255, 0, 0));

        txtentejob.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentejob.setForeground(new java.awt.Color(255, 0, 0));

        txteaddr.setColumns(20);
        txteaddr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txteaddr.setRows(5);
        txteaddr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txteaddrKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txteaddr);

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(124, 124, 124)
                        .addComponent(btnhome))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)))
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtentesal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtentephno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtenteaddr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtentefname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtelname)
                            .addComponent(txteid)
                            .addComponent(txtefname)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtegen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtephno)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtesal)
                            .addComponent(txtejob)
                            .addComponent(txtenteid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtentelname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtentjDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtentegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtentjDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtentejob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnupdate))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnrefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(btnsearch)))
                        .addGap(201, 201, 201)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(imagePanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(92, 92, 92))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtenteid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtefname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtentefname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtelname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtentelname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(158, 158, 158)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtenteaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtentjDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtegen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtentegen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtephno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtentephno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtentjDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtesal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtentesal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtejob, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtentejob, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txteidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteidActionPerformed
                     // TODO add your handling code here:
    }//GEN-LAST:event_txteidActionPerformed

    private void txtefnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtefnameActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_txtefnameActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try {
            String sql2 = "select * from employee where EmpID=?;";
            pst = conn.prepareStatement(sql2);
            pst.setString(1, txteid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txteid.setText(rs.getString(1));
                txtefname.setText(rs.getString(2));
                txtelname.setText(rs.getString(3));
                jDateChooser1.setDate(rs.getDate(4));
                txtegen.setSelectedItem(rs.getString(5));
                txteaddr.setText(rs.getString(6));
                txtephno.setText(rs.getString(7));
                txtejob.setText(rs.getString(8));
                jDateChooser2.setDate(rs.getDate(9));
                txtesal.setText(rs.getString(10));
            }
           
            else {
                JOptionPane.showMessageDialog(null, " incorrect EmpID");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
     if (txteid.getText().trim().isEmpty() && txtefname.getText().trim().isEmpty() && txtelname.getText().trim().isEmpty() && txteaddr.getText().trim().isEmpty() && ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText().trim().isEmpty() && txtegen.getSelectedItem().toString().trim().isEmpty() && txtephno.getText().trim().isEmpty()  && ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText().trim().isEmpty() && txtesal.getText().trim().isEmpty()  && txtejob.getText().trim().isEmpty()) {
            txtenteid.setText("Enter  Emp ID");
            txtentefname.setText("Enter  FName");
            txtentelname.setText("Enter LName");
            txtenteaddr.setText("Enter Address");
            txtentjDateChooser1.setText("Enter Date Of Birth");
            txtentegen.setText("Enter Gender");
            txtenteaddr.setText("Enter Address");
            txtentephno.setText("Enter Phno");
            txtentjDateChooser2.setText("Enter Join Date");
             txtentesal.setText("Enter Salary");
             txtentejob.setText("Enter Job Title");

        } else if (txteid.getText().trim().isEmpty()) {
             txtenteid.setText("Enter  Emp ID");
        } else if (txtefname.getText().trim().isEmpty()) {
            txtentefname.setText("Enter  FName");
        } else if (txtelname.getText().trim().isEmpty()) {
          txtentelname.setText("Enter LName");
        } else if (txteaddr.getText().trim().isEmpty()) { 
         txtenteaddr.setText("Enter Address");
        } else if (((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText().trim().isEmpty()) {
           txtentjDateChooser1.setText("Enter Date Of Birth");
        } else if (txtegen.getSelectedItem().toString().trim().isEmpty()) {
           txtentegen.setText("Enter Gender");
        } else if (txteaddr.getText().trim().isEmpty()) { 
        txtenteaddr.setText("Enter Address");
        } else if (txtephno.getText().trim().isEmpty()) {
             txtentephno.setText("Enter Phno");
        }  else if (((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText().trim().isEmpty()) {
           txtentjDateChooser2.setText("Enter Join Date");
           } else if (txtesal.getText().trim().isEmpty()) {
             txtentesal.setText("Enter Salary");
         } else if (txtejob.getText().trim().isEmpty()) {
          txtentejob.setText("Enter Job Title");
        } else {  
        Pattern p=Pattern.compile("^[6-9][0-9]{9}$");
       Matcher m=p.matcher(txtephno.getText());
       if(!m.matches())
         {
           
           JOptionPane.showMessageDialog(null, "Invalid Phone Number","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }
        String date = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
        System.out.println(date);
        
        try {
            if (Command == UPDATE) {
                String sql = "update employee set  EmpID=?,"
                        + "FName=?,LName=?,DateOfBirth=?,Gender=?,"
                        + "Address=?,PhNo=?,JobTitle=? ,"
                        + "JoinDate=?,Salary=? "
                        + "where EmpID=?";

                pst = conn.prepareStatement(sql);
                pst.setString(1, txteid.getText());
                pst.setString(2, txtefname.getText());
                pst.setString(3, txtelname.getText());
                pst.setString(4, ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText());
                pst.setString(5, txtegen.getSelectedItem().toString());
                pst.setString(6, txteaddr.getText());
                pst.setString(7, txtephno.getText());
                pst.setString(8, txtejob.getText());
                pst.setString(9, ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText());
                pst.setString(10, txtesal.getText());
                pst.setString(11, txteid.getText());
                JOptionPane.showMessageDialog(null, "updated sucessfuly");
                pst.executeUpdate();
                
                
                btnadd.setVisible(true);
                btndelete.setVisible(true);
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                txteid.setText("");
                txtefname.setText("");
                txtelname.setText("");
                ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText("");
                txtegen.setToolTipText("Male");
                txteaddr.setText("");
                txtephno.setText("");
                txtejob.setText("");
                ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).setText("");
                txtesal.setText("");
            } else if (Command == ADD) {
                String sql = "Insert into employee (EmpID,FName,LName,DateOfBirth,Gender,Address,PhNo,JobTitle,JoinDate,Salary) values (?,?,?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txteid.getText());
                pst.setString(2, txtefname.getText());
                pst.setString(3, txtelname.getText());
                pst.setString(4, ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText());
                pst.setString(5, txtegen.getSelectedItem().toString());
                pst.setString(6, txteaddr.getText());
                pst.setString(7, txtephno.getText());
                pst.setString(8, txtejob.getText());
                pst.setString(9, ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText());
                pst.setString(10, txtesal.getText());
                JOptionPane.showMessageDialog(null, "inserted successfully");
                pst.executeUpdate();
                String IDUpdateQry = "Update autogen SET EmpID=?";

                pst = conn.prepareStatement(IDUpdateQry);
                pst.setString(1, "" + (Integer.parseInt(txteid.getText()) + (int) 1));
                pst.executeUpdate();
                
                btnadd.setVisible(true);
                btndelete.setVisible(true);
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                txteid.setText("");
                txtefname.setText("");
                txtelname.setText("");
                ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText("");
                txtegen.setSelectedItem("Male");
                txteaddr.setText("");
                txtephno.setText("");
                txtejob.setText("");
                ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).setText("");
                txtesal.setText("");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
}
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        setVisible(false);
        HomePage ob = new HomePage();
        ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
       try {
        txteid.setText("");
        txtefname.setText("");
        txtelname.setText("");
        ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText("");
        txtegen.setToolTipText("Male");
        txteaddr.setText("");
        txtephno.setText("");
        txtejob.setText("");
        ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).setText("");
        txtesal.setText("");

        btndelete.setVisible(false);
        btnupdate.setVisible(false);
        btnsave.setVisible(true);
        btnsearch.setVisible(true);
        Command = ADD;
        
        String getIDQry = "Select EmpID FROM autogen;";
            pst = conn.prepareStatement(getIDQry);
            rs = pst.executeQuery();
            
              if (rs.next()) {
                txteid.setText(rs.getString("EmpID"));
            } else {
                JOptionPane.showMessageDialog(null, "Unknown Error!!");
            }
              } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are u sure u want to delete?", "delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from employee where EmpID=?";
            try {

                pst = conn.prepareStatement(sql);
                pst.setString(1, txteid.getText());
               
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "deleted sucessfuly");
                
                
                String IDUpdateQry = "Update autogen SET EmpID=?";

                pst = conn.prepareStatement(IDUpdateQry);
                pst.setString(1, "" + (Integer.parseInt(txteid.getText()) - (int) 1));
                
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                btnadd.setVisible(true);
                txteid.setText("");
                txtefname.setText("");
                txtelname.setText("");
                ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText("");
                txtegen.setToolTipText("Male");
                txteaddr.setText("");
                txtephno.setText("");
                txtejob.setText("");
                ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).setText("");
                txtesal.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {

            txtefname.setText("");
            txtelname.setText("");
            ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText("");
            txtegen.setToolTipText("Male");
            txteaddr.setText("");
            txtephno.setText("");
            txtejob.setText("");
            ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).setText("");
            txtesal.setText("");

            txtefname.setEnabled(true);
            txtelname.setEnabled(true);
            txtegen.setEnabled(true);
            txteaddr.setEnabled(true);
            txtephno.setEnabled(true);
            txtejob.setEnabled(true);
            jDateChooser1.setEnabled(true);
            jDateChooser2.setEnabled(true);
            txtesal.setEnabled(true);
            Command = UPDATE;
            
            btndelete.setVisible(false);
            btnadd.setVisible(false);
            
             String sql2 = "select * from employee where EmpID=?;";
            pst = conn.prepareStatement(sql2);
            pst.setString(1, txteid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txteid.setText(rs.getString(1));
                txtefname.setText(rs.getString(2));
                txtelname.setText(rs.getString(3));
                jDateChooser1.setDate(rs.getDate(4));
                txtegen.setSelectedItem(rs.getString(5));
                txteaddr.setText(rs.getString(6));
                txtephno.setText(rs.getString(7));
                txtejob.setText(rs.getString(8));
                jDateChooser2.setDate(rs.getDate(9));
                txtesal.setText(rs.getString(10));
            }
            else {
                JOptionPane.showMessageDialog(null, " incorrect EmpID");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }                                          // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        txteid.setText("");
        txtefname.setText("");
        txtelname.setText("");
        ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText("");
        txtegen.setToolTipText("Male");
        txteaddr.setText("");
        txtephno.setText("");
        txtejob.setText("");
        ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).setText("");
        txtesal.setText(""); 
        txteid.setEnabled(true);
        
         btnadd.setVisible(true);
        btndelete.setVisible(true);
        btnsave.setVisible(true);
        btnsearch.setVisible(true);
        btnupdate.setVisible(true);

    }//GEN-LAST:event_btnrefreshActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
         URL resource = getClass().getResource("/iconandpictures/pexelsemployee.jpeg");

        try {
           // System.out.println(Paths.get(resource.toURI()).toFile().getAbsolutePath());
            imagePanel1.setImage(new ImageIcon(resource).getImage(),
                    this.getWidth(), this.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formComponentResized

    private void txtephnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtephnoActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_txtephnoActionPerformed

    private void txtesalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtesalActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_txtesalActionPerformed

    private void imagePanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagePanel1ComponentResized
        URL resource = getClass().getResource("/iconandpictures/pexelsemployee.jpg");

        try {
          //  System.out.println(Paths.get(resource.toURI()).toFile().getAbsolutePath());
            imagePanel1.setImage(new ImageIcon(resource).getImage(),
                    this.getWidth(), this.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_imagePanel1ComponentResized

    private void txtelnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtelnameActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtelnameActionPerformed

    private void txtegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtegenActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtegenActionPerformed

    private void txtejobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtejobActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtejobActionPerformed

    private void txtegenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtegenKeyTyped
       txtentegen.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_txtegenKeyTyped

    private void txtesalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtesalKeyTyped
        txtentesal.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtesalKeyTyped

    private void txtejobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtejobKeyTyped
        txtentejob.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtejobKeyTyped

    private void txtephnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtephnoKeyTyped
        txtentephno.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtephnoKeyTyped

    private void txtelnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtelnameKeyTyped
        txtentelname.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtelnameKeyTyped

    private void txtefnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtefnameKeyTyped
        txtentefname.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtefnameKeyTyped

    private void txteidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteidKeyTyped
        txtenteid.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txteidKeyTyped

    private void txteaddrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteaddrKeyTyped
       txtenteaddr.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txteaddrKeyTyped

    private void jDateChooser1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyTyped
        txtentjDateChooser1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1KeyTyped

    private void jDateChooser2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser2KeyTyped
       txtentjDateChooser2.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2KeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Employee().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private coffee.ImagePanel imagePanel1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txteaddr;
    private javax.swing.JTextField txtefname;
    private javax.swing.JComboBox<String> txtegen;
    private javax.swing.JTextField txteid;
    private javax.swing.JTextField txtejob;
    private javax.swing.JTextField txtelname;
    private javax.swing.JLabel txtenteaddr;
    private javax.swing.JLabel txtentefname;
    private javax.swing.JLabel txtentegen;
    private javax.swing.JLabel txtenteid;
    private javax.swing.JLabel txtentejob;
    private javax.swing.JLabel txtentelname;
    private javax.swing.JLabel txtentephno;
    private javax.swing.JLabel txtentesal;
    private javax.swing.JLabel txtentjDateChooser1;
    private javax.swing.JLabel txtentjDateChooser2;
    private javax.swing.JTextField txtephno;
    private javax.swing.JTextField txtesal;
    // End of variables declaration//GEN-END:variables
}
