/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author abcd
 */
public class Item extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    static Integer Command;

    int ADD = 0;
    int UPDATE = 1;

    /**
     * Creates new form Items
     */
    public Item() {
        super("Item");
        initComponents();
        conn = dbconnect.connectdb();
        FrameInit();
        setCategoryModel();
        URL resource = getClass().getResource("/iconandpictures/Blank.jpg");

        try {
            imagePanel2.setImage(new ImageIcon(resource).getImage(),
                    imagePanel2.getWidth(), imagePanel2.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void FrameInit() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim);             ///This will let frame initialise in full screen
        //txtitemid.setEnabled(false);
        txtitemname.setEnabled(false);
        txtprice.setEnabled(false);
        txtflavour.setEnabled(false);
        ComboCatname.setEnabled(false);
        txtcatid.setEnabled(false);
        txtpic.setEnabled(false);

    }

    public Item(String ItemID, String ItemName, String Price, String Flavour, String CategoryName, String CategoryID, String Picture) {
        super("Item");
        initComponents();
        conn = dbconnect.connectdb();
        FrameInit();
        setCategoryModel();
        txtitemid.setText(ItemID);
        txtitemname.setText(ItemName);
        txtprice.setText(Price);
        txtflavour.setText(Flavour);
        ComboCatname.setSelectedItem(CategoryName);
        txtcatid.setText(CategoryID);
        txtpic.setText(Picture);
        imagePanel2.setImage(new ImageIcon(Picture).getImage(),
                imagePanel2.getWidth(), imagePanel2.getHeight());
    }

    private void setCategoryModel() {
        try {
            txtcatid.setEnabled(false);
            String Qry = "SELECT CategoryName from category;";
            pst = conn.prepareStatement(Qry);
            rs = pst.executeQuery();

            while (rs.next()) {
                System.out.println(rs.getString("CategoryName"));
                ComboCatname.addItem(rs.getString("CategoryName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new coffee.ImagePanel();
        btnsave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        txtitemid = new javax.swing.JTextField();
        txtitemname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtflavour = new javax.swing.JTextField();
        txtcatid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ComboCatname = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtpic = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtentpicture = new javax.swing.JLabel();
        imagePanel2 = new coffee.ImagePanel();
        txtlid = new javax.swing.JLabel();
        txtlname = new javax.swing.JLabel();
        txtlflavour = new javax.swing.JLabel();
        txtlprice = new javax.swing.JLabel();
        txtlcname = new javax.swing.JLabel();
        txtlcid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/save.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 70)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("ITEM");

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/delete.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/add.png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/Update.png"))); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/search.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnhome.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/home.png"))); // NOI18N
        btnhome.setText("HOME");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        txtitemid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtitemid.setPreferredSize(new java.awt.Dimension(250, 40));
        txtitemid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtitemidFocusLost(evt);
            }
        });
        txtitemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemidActionPerformed(evt);
            }
        });
        txtitemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtitemidKeyTyped(evt);
            }
        });

        txtitemname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtitemname.setPreferredSize(new java.awt.Dimension(250, 40));
        txtitemname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtitemnameKeyTyped(evt);
            }
        });

        txtprice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtprice.setPreferredSize(new java.awt.Dimension(250, 40));
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpriceKeyTyped(evt);
            }
        });

        txtflavour.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtflavour.setPreferredSize(new java.awt.Dimension(250, 40));
        txtflavour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtflavourKeyTyped(evt);
            }
        });

        txtcatid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcatid.setPreferredSize(new java.awt.Dimension(250, 40));
        txtcatid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcatidActionPerformed(evt);
            }
        });
        txtcatid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcatidKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setText("Picture");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setText("Flavour");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setText("Price");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Item Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("Item ID");

        btnrefresh.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/settings.png"))); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setText("Category Name");

        ComboCatname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ComboCatname.setPreferredSize(new java.awt.Dimension(66, 40));
        ComboCatname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCatnameItemStateChanged(evt);
            }
        });
        ComboCatname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCatnameActionPerformed(evt);
            }
        });
        ComboCatname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComboCatnameKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setText("Category ID");

        txtpic.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtpic.setPreferredSize(new java.awt.Dimension(250, 40));
        txtpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpicActionPerformed(evt);
            }
        });
        txtpic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpicKeyTyped(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtentpicture.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtentpicture.setForeground(new java.awt.Color(255, 0, 0));

        imagePanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        txtlid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlid.setForeground(new java.awt.Color(255, 0, 51));

        txtlname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlname.setForeground(new java.awt.Color(255, 0, 51));

        txtlflavour.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlflavour.setForeground(new java.awt.Color(255, 0, 51));

        txtlprice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtlprice.setForeground(new java.awt.Color(255, 0, 51));

        txtlcname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlcname.setForeground(new java.awt.Color(255, 0, 51));

        txtlcid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlcid.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlid, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcatid, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtlcid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtentpicture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtpic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(385, 385, 385)
                        .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtlcname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlflavour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtitemid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtflavour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtitemname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboCatname, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnrefresh)
                                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96))))))
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhome)
                .addGap(175, 175, 175))
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel3))
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtitemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtlid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtitemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel5))
                                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                                .addComponent(txtflavour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtlflavour, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlprice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboCatname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addComponent(txtlcname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcatid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addComponent(txtlcid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtpic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(txtentpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try {
            txtitemid.setText("");
            txtitemname.setText("");
            txtprice.setText("");
            txtflavour.setText("");
            ComboCatname.setToolTipText("");
            txtcatid.setText("");
            txtitemid.setEnabled(false);
            txtflavour.setEnabled(true);
            txtitemname.setEnabled(true);
            txtprice.setEnabled(true);
            txtflavour.setEnabled(true);
            ComboCatname.setEnabled(true);
            txtcatid.setEnabled(false);
            btndelete.setVisible(false);
            btnupdate.setVisible(false);   
            btnsave.setVisible(true);
            btnsearch.setVisible(true);
            Command = ADD;

            String getIDQry = "Select ItemID FROM autogen;";
            pst = conn.prepareStatement(getIDQry);
            rs = pst.executeQuery();

            if (rs.next()) {
                txtitemid.setText(rs.getString("ItemID"));
            } else {
                JOptionPane.showMessageDialog(null, "Unknown Error!!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtcatidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcatidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcatidActionPerformed

    private void txtitemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemidActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        setVisible(false);
        HomePage ob = new HomePage();
        ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are u sure u want to delete?", "delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from item where ItemID=?";
            try {

                pst = conn.prepareStatement(sql);
                pst.setString(1, txtitemid.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "deleted sucessfuly");

                String IDUpdateQry = "Update autogen SET ItemID=?";

                pst = conn.prepareStatement(IDUpdateQry);
                pst.setString(1, "" + (Integer.parseInt(txtitemid.getText()) - (int) 1));

                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                btnadd.setVisible(true);
                txtitemid.setText("");
                txtitemname.setText("");
                txtprice.setText("");
                txtflavour.setText("");
                ComboCatname.setToolTipText("");
                txtcatid.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        txtitemid.setEnabled(true);
        try {

            String sql2 = "SELECT * FROM item WHERE ItemID=?";
            pst = conn.prepareStatement(sql2);
            pst.setString(1, txtitemid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtitemid.setText(rs.getString("ItemID"));
                txtitemname.setText(rs.getString(2));
                txtprice.setText(rs.getString(3));
                txtflavour.setText(rs.getString(4));
                ComboCatname.setSelectedItem(rs.getString(5));
                txtcatid.setText(rs.getString(6));
                txtpic.setText(rs.getString(7));
            } else {
                JOptionPane.showMessageDialog(null, "incorrect ItemID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {

            txtitemname.setText("");
            txtprice.setText("");
            txtflavour.setText("");
            ComboCatname.setToolTipText("");
            txtcatid.setText("");
            txtitemid.setEnabled(true);
            txtflavour.setEnabled(true);
            txtitemname.setEnabled(true);
            txtprice.setEnabled(true);
            txtflavour.setEnabled(true);
            ComboCatname.setEnabled(true);
            txtcatid.setEnabled(true);
            Command = UPDATE;
            
            btnupdate.setVisible(true);
            btnadd.setVisible(false);
            btndelete.setVisible(false);
            
            
            String sql2 = "SELECT * FROM item WHERE ItemID=?";
            pst = conn.prepareStatement(sql2);
            pst.setString(1, txtitemid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtitemid.setText(rs.getString("ItemID"));
                txtitemname.setText(rs.getString(2));
                txtprice.setText(rs.getString(3));
                txtflavour.setText(rs.getString(4));
                ComboCatname.setSelectedItem(rs.getString(5));
                txtcatid.setText(rs.getString(6));
                txtpic.setText(rs.getString(7));
            } else {
                JOptionPane.showMessageDialog(null, "incorrect ItemID");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }                                 // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            if (Command == UPDATE) {
                String sql = "update item set ItemID=?,"
                        + "ItemName=?,Price=?,Flavour=?,"
                        + "CategoryName=?,CategoryID=?,Picture=?"
                        + "where ItemID=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtitemid.getText());
                pst.setString(2, txtitemname.getText());
                pst.setString(3, txtprice.getText());
                pst.setString(4, txtflavour.getText());
                pst.setString(5, ComboCatname.getToolTipText());
                pst.setString(6, txtcatid.getText());
                pst.setString(7, txtitemid.getText() + "." + getFileExtension(new File(txtpic.getText())));
                pst.setString(8, txtitemid.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "updated sucessfuly");
                txtitemid.setText("");
                txtitemname.setText("");
                txtprice.setText("");
                txtflavour.setText("");
                ComboCatname.setToolTipText("");
                
                txtcatid.setText("");
                btndelete.setVisible(true);
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                btnadd.setVisible(true);
            } else if (Command == ADD) {

                CopyFile(new File(txtpic.getText()).toPath(), txtitemid.getText());
                String sql = "Insert into item (ItemID,ItemName,Price,Flavour,CategoryName,CategoryID,Picture) values (?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtitemid.getText());
                pst.setString(2, txtitemname.getText());
                pst.setString(3, txtprice.getText());
                pst.setString(4, txtflavour.getText());
                pst.setString(5, ComboCatname.getSelectedItem().toString());
                pst.setString(6, txtcatid.getText());
                pst.setString(7, txtitemid.getText() + "." + getFileExtension(new File(txtpic.getText())));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "inserted successfully");
                String IDUpdateQry = "Update autogen SET ItemID=?";

                pst = conn.prepareStatement(IDUpdateQry);
                pst.setString(1, "" + (Integer.parseInt(txtitemid.getText()) + (int) 1));
                pst.executeUpdate();

                btndelete.setVisible(true);
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                txtitemid.setText("");
                txtitemname.setText("");
                txtprice.setText("");
                txtflavour.setText("");
                ComboCatname.setToolTipText("");
                txtcatid.setText("");
                btndelete.setVisible(true);
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                btnadd.setVisible(true);
            }
            //txtitemname.setEnabled(false);
            //txtprice.setEnabled(false);
            //txtflavour.setEnabled(false);
            //txtcatname.setEnabled(false);
            //txtcatid.setEnabled(false);

        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setVisible(false);
            new Item().setVisible(true);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void ComboCatnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCatnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCatnameActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        txtitemid.setText("");
        txtitemname.setText("");
        txtprice.setText("");
        txtflavour.setText("");
        ComboCatname.setToolTipText("");
        txtcatid.setText("");
        txtpic.setText("");
         btnadd.setVisible(true);
        btndelete.setVisible(true);
        btnsave.setVisible(true);
        btnsearch.setVisible(true);
        btnupdate.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void txtpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpicActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        FrameSet();
    }//GEN-LAST:event_formComponentResized

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser j = new JFileChooser();
        int ret = j.showOpenDialog(this);

        if (ret == JFileChooser.APPROVE_OPTION) {

            this.setVisible(false);
            new Item(
                    txtitemid.getText(),
                    txtitemname.getText(),
                    txtprice.getText(),
                    txtflavour.getText(),
                    ComboCatname.getSelectedItem().toString(),
                    txtcatid.getText(),
                    j.getSelectedFile().getAbsolutePath()
            ).setVisible(true);
        } else {
            txtpic.setText(txtpic.getText());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtitemidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtitemidFocusLost
        try {
            txtitemid.setEnabled(false);
            String sql2 = "SELECT * FROM item WHERE ItemID=?";
            pst = conn.prepareStatement(sql2);
            pst.setString(1, txtitemid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtitemid.setText(rs.getString("ItemID"));
                txtitemname.setText(rs.getString(2));
                txtprice.setText(rs.getString(3));
                txtflavour.setText(rs.getString(4));
                ComboCatname.setToolTipText(rs.getString(5));
                txtcatid.setText(rs.getString(6));
            } else {
                JOptionPane.showMessageDialog(null, "incorrect ItemID");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

            // TODO add your handling code here:
        }
    }//GEN-LAST:event_txtitemidFocusLost

    private void ComboCatnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCatnameItemStateChanged
        try {
            Connection connL;
            connL = dbconnect.connectdb();
            ResultSet rsL;
            PreparedStatement pstL;
            String SelectedItem = ComboCatname.getSelectedItem().toString();
            String Qry = "select CategoryID from category where CategoryName = '" + SelectedItem + "';";

            pstL = connL.prepareStatement(Qry);
            rsL = pstL.executeQuery();
            if (rsL.next()) {
                txtcatid.setText(rsL.getString("CategoryId"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ComboCatnameItemStateChanged

    private void txtitemidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemidKeyTyped
        txtlid.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtitemidKeyTyped

    private void txtitemnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemnameKeyTyped
       txtlname.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_txtitemnameKeyTyped

    private void txtpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyTyped
        txtlprice.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtpriceKeyTyped

    private void txtflavourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtflavourKeyTyped
       txtlflavour.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_txtflavourKeyTyped

    private void txtcatidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcatidKeyTyped
        txtlcid.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtcatidKeyTyped

    private void ComboCatnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboCatnameKeyTyped
       txtlcname.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_ComboCatnameKeyTyped

    private void txtpicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpicKeyTyped
        txtentpicture.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_txtpicKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Item().setVisible(true);
//            }
//        });
//    }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCatname;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private coffee.ImagePanel imagePanel1;
    private coffee.ImagePanel imagePanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcatid;
    private javax.swing.JLabel txtentpicture;
    private javax.swing.JTextField txtflavour;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JTextField txtitemname;
    private javax.swing.JLabel txtlcid;
    private javax.swing.JLabel txtlcname;
    private javax.swing.JLabel txtlflavour;
    private javax.swing.JLabel txtlid;
    private javax.swing.JLabel txtlname;
    private javax.swing.JLabel txtlprice;
    private javax.swing.JTextField txtpic;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables

    private void FrameSet() {
        URL resource = getClass().getResource("/iconandpictures/itemsback1.jpg");

        try {
            //System.out.println(Paths.get(resource.toURI()).toFile().getAbsolutePath());
            imagePanel1.setImage(new ImageIcon(resource).getImage(),
                    this.getWidth(), this.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CopyFile(Path Source, String ItemId) throws IOException {
        {
            try {
                Path Dest = Paths.get("." + "\\src\\UserImages\\Item_" + ItemId + "." + getFileExtension(Source.toFile()));
                Files.copy(Source, Dest, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private static String getFileExtension(File file) {
        String fileName = file.getName();
        if (fileName.lastIndexOf(".") != -1 && fileName.lastIndexOf(".") != 0) {
            return fileName.substring(fileName.lastIndexOf(".") + 1);
        } else {
            return "";
        }
    }

    private static boolean validate(String Email) {         /// Code for Email validation
        if (Email.indexOf('@') != -1) {
            {
                if (Email.endsWith(".com")) {
                    return true;

                }
            }
        }
        return false;
    }
}
