/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author H.N Nayanashree
 */
public class Login extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form Login
     */
    public Login() {
        super("Login");
        initComponents();
        conn = dbconnect.connectdb();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        txtuname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnforgot = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtentuser = new javax.swing.JLabel();
        txtentpass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("UserName");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 230, 190, 36);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 340, 140, 36);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("LOGIN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 60, 230, 71);

        btnexit.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/exit.png"))); // NOI18N
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit);
        btnexit.setBounds(800, 60, 150, 50);

        txtuname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        txtuname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtunameKeyReleased(evt);
            }
        });
        jPanel1.add(txtuname);
        txtuname.setBounds(360, 230, 250, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Trouble Login!!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 570, 170, 28);

        btnlogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/sign-in (2).png"))); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(350, 500, 120, 50);

        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/settings.png"))); // NOI18N
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset);
        btnreset.setBounds(520, 500, 120, 50);

        btnforgot.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnforgot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/forgotpassword.png"))); // NOI18N
        btnforgot.setText("FORGOT PASSWORD");
        btnforgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgotActionPerformed(evt);
            }
        });
        jPanel1.add(btnforgot);
        btnforgot.setBounds(360, 600, 250, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/if_102_111044 (1).png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(650, 240, 24, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/icons8-password-1-26.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(650, 330, 26, 26);

        txtpassword.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });
        jPanel1.add(txtpassword);
        txtpassword.setBounds(360, 350, 250, 40);

        txtentuser.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        txtentuser.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtentuser);
        txtentuser.setBounds(370, 280, 240, 20);

        txtentpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtentpass.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(txtentpass);
        txtentpass.setBounds(360, 410, 240, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/back3.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        if (txtuname.getText().trim().isEmpty() && txtpassword.getText().trim().isEmpty()) {
            txtentuser.setText("Enter  Username");
            txtentpass.setText("Enter Password");

        } else if (txtuname.getText().trim().isEmpty()) {
            txtentuser.setText("Enter  Username");
        } else if (txtpassword.getText().trim().isEmpty()) {
            txtentpass.setText("Enter Password");
        } else {  //is  this code kk
            String sql = "select * from login where Username='" + txtuname.getText().trim() + "' and Password='" + txtpassword.getText().trim() + "';";

            try {
                pst = conn.prepareStatement(sql);

                rs = pst.executeQuery();
                if (rs.next()) {
                    rs.close();
                    pst.close();
                    JOptionPane.showMessageDialog(null, "Login Success!!!");
                    setVisible(false);
                    Loading ob = new Loading();
                    ob.setUpprogressbar();
                    ob.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "incorrect username or password");
                    txtuname.setText("");
                    txtpassword.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
                // Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } //        catch(Exception e){
            //             JOptionPane.showMessageDialog(null,e);
            finally {
                try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {

                }
// TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed
        }
    }
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtuname.setText("");
        txtpassword.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnforgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgotActionPerformed
        setVisible(false);
        ForgotPasswords ob = new ForgotPasswords();
        ob.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnforgotActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtunameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunameKeyReleased
        txtentuser.setText("");

    }//GEN-LAST:event_txtunameKeyReleased

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
        txtentpass.setText("");
    }//GEN-LAST:event_txtpasswordKeyReleased

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
      this.dispose();

    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnforgot;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtentpass;
    private javax.swing.JLabel txtentuser;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
