/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author H.N Nayanashree
 */
public class Order extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Integer Command;
    CallableStatement cs;

    int ADD = 0;
    int UPDATE = 1;

    /**
     * Creates new form Orders
     */
    public Order() {
        super("Order");
        initComponents();
        conn = dbconnect.connectdb();
        FrameInit();
    }

    private void FrameInit() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim);             ///This will let frame initialise in full screen
        setItemModel();
        setCustNameModel();
    }

    private void setItemModel() {
        try {
            txtitemid.setEnabled(false);
            String Qry = "Select ItemName from item;";
            pst = conn.prepareStatement(Qry);
            rs = pst.executeQuery();

            while (rs.next()) {
                System.out.println(rs.getString("ItemName"));
                ComboItemName.addItem(rs.getString("ItemName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setCustNameModel() {
        try {
            txtcustid.setEnabled(false);
            String Qry = "SELECT CustName FROM customer;";
            pst = conn.prepareStatement(Qry);
            rs = pst.executeQuery();

            while (rs.next()) {
                System.out.println(rs.getString("CustName"));
                ComboCustName.addItem(rs.getString("CustName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new coffee.ImagePanel();
        jLabel10 = new javax.swing.JLabel();
        ComboCustName = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        txtempid = new javax.swing.JTextField();
        txttotalamt = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txtcustid = new javax.swing.JTextField();
        txtitemid = new javax.swing.JTextField();
        txtoid = new javax.swing.JTextField();
        btnhome = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        ComboItemName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtentoid = new javax.swing.JLabel();
        txtentcomboitemname = new javax.swing.JLabel();
        txtentitemid = new javax.swing.JLabel();
        txtentcustname = new javax.swing.JLabel();
        txtentcustid = new javax.swing.JLabel();
        txtentqty = new javax.swing.JLabel();
        txtentprice = new javax.swing.JLabel();
        txtenttotalamt = new javax.swing.JLabel();
        txtentempid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setText(" Customer Name");

        ComboCustName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ComboCustName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCustNameItemStateChanged(evt);
            }
        });
        ComboCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCustNameActionPerformed(evt);
            }
        });
        ComboCustName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComboCustNameKeyTyped(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/save.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/Update.png"))); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/search.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/delete.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/add.png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        txtempid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempidActionPerformed(evt);
            }
        });
        txtempid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtempidKeyTyped(evt);
            }
        });

        txttotalamt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txttotalamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalamtActionPerformed(evt);
            }
        });
        txttotalamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttotalamtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttotalamtKeyTyped(evt);
            }
        });

        txtprice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpriceKeyTyped(evt);
            }
        });

        txtqty.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        txtqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtqtyKeyTyped(evt);
            }
        });

        txtcustid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustidActionPerformed(evt);
            }
        });
        txtcustid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcustidKeyTyped(evt);
            }
        });

        txtitemid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtitemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemidActionPerformed(evt);
            }
        });
        txtitemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtitemidKeyTyped(evt);
            }
        });

        txtoid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtoid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtoidKeyTyped(evt);
            }
        });

        btnhome.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/home.png"))); // NOI18N
        btnhome.setText("HOME");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setText("Emp ID");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setText("Total Amount");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setText("Price");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setText("Customer ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setText("Item ID");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel12.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setText("Order ID");

        btnrefresh.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconandpictures/settings.png"))); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        ComboItemName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ComboItemName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboItemNameItemStateChanged(evt);
            }
        });
        ComboItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComboItemNameKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("ORDER");

        txtentoid.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentoid.setForeground(new java.awt.Color(255, 51, 0));

        txtentcomboitemname.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentcomboitemname.setForeground(new java.awt.Color(255, 0, 0));

        txtentitemid.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentitemid.setForeground(new java.awt.Color(255, 0, 0));

        txtentcustname.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentcustname.setForeground(new java.awt.Color(255, 0, 0));

        txtentcustid.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentcustid.setForeground(new java.awt.Color(255, 0, 0));

        txtentqty.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentqty.setForeground(new java.awt.Color(255, 0, 0));

        txtentprice.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentprice.setForeground(new java.awt.Color(255, 0, 0));

        txtenttotalamt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtenttotalamt.setForeground(new java.awt.Color(255, 0, 0));

        txtentempid.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtentempid.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imagePanel1Layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcustid)
                                    .addComponent(ComboItemName, 0, 250, Short.MAX_VALUE)
                                    .addComponent(txtentoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtentcomboitemname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtentcustid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtqty)
                                    .addComponent(txtentqty, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtentcustname, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtentprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttotalamt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtenttotalamt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtempid, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addGroup(imagePanel1Layout.createSequentialGroup()
                                        .addComponent(txtentempid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(147, 147, 147)))
                                .addGap(7, 7, 7)))
                        .addGap(95, 95, 95)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGap(448, 448, 448)
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(imagePanel1Layout.createSequentialGroup()
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtitemid, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(txtentitemid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(203, 203, 203)
                                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnrefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(416, 735, Short.MAX_VALUE))
            .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(imagePanel1Layout.createSequentialGroup()
                    .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagePanel1Layout.createSequentialGroup()
                            .addGap(1342, 1342, 1342)
                            .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(imagePanel1Layout.createSequentialGroup()
                            .addGap(292, 292, 292)
                            .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(229, Short.MAX_VALUE)))
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtentoid, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComboItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtentcomboitemname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtitemid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addComponent(txtentitemid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtentcustname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(1, 1, 1)
                        .addComponent(txtentcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtentqty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtentprice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txttotalamt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtenttotalamt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtempid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtentempid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(imagePanel1Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(882, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        setVisible(false);
        HomePage ob = new HomePage();
        ob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        txtoid.setEnabled(true);
        txttotalamt.setEnabled(false);
        try {

            String sql2 = "SELECT * FROM `orders` WHERE OrderID ='"+txtoid.getText()+"';";
            pst = conn.prepareStatement(sql2);
            //pst.setString(1, ComboCustName.getSelectedItem().toString());
          
            rs = pst.executeQuery();
            if (rs.next()) {
                //txtoid.setText(rs.getString("OrderID"));
                
                ComboItemName.setSelectedItem(rs.getString("ItemName"));
                txtitemid.setText(rs.getString("ItemID"));
                ComboCustName.setSelectedItem(rs.getString("CustName"));
                txtcustid.setText(rs.getString("CustID"));
                txtqty.setText(rs.getString("Quantity"));
                txtprice.setText(rs.getString("Price"));
                txttotalamt.setText(rs.getString("TotalAmt"));
                txtempid.setText(rs.getString("EmpID"));
                

            } else {
                JOptionPane.showMessageDialog(null, "incorrect OrderID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try {
            txtoid.setText("");
            ComboItemName.setToolTipText("");
            txtitemid.setText("");
            ComboCustName.setToolTipText("");
            txtcustid.setText("");
            txtqty.setText("");
            txtprice.setText("");

            txttotalamt.setText("");
            txtempid.setText("");
            btndelete.setVisible(false);
            btnupdate.setVisible(false);
            btnsave.setVisible(true);
            btnsearch.setVisible(true);
            Command = ADD;
            txttotalamt.setEnabled(false);

            String getIDQry = "Select OrderID FROM autogen;";
            pst = conn.prepareStatement(getIDQry);
            rs = pst.executeQuery();
            if (rs.next()) {
                txtoid.setText(rs.getString("OrderID"));
            } else {
                JOptionPane.showMessageDialog(null, "Unknown Error!!");
            }
        } catch (Exception ex) {
            Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        int p = JOptionPane.showConfirmDialog(null, "Are u sure u want to delete?", "delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from orders where OrderID=?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtoid.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "deleted sucessfuly");

                String IDUpdateQry = "Update autogen SET OrderID=?";

                pst = conn.prepareStatement(IDUpdateQry);
                pst.setString(1, "" + (Integer.parseInt(txtoid.getText()) - (int) 1));

                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                btnadd.setVisible(true);
                txtoid.setText("");
                ComboItemName.setToolTipText("");
                txtitemid.setText("");
                ComboCustName.setToolTipText("");
                txtcustid.setText("");
                txtqty.setText("");
                txtprice.setText("");

                txttotalamt.setText("");
                txtempid.setText("");
                txttotalamt.setEnabled(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        if (txtoid.getText().trim().isEmpty() && ComboItemName.getSelectedItem().toString().trim().isEmpty() && txtitemid.getText().trim().isEmpty() && ComboCustName.getSelectedItem().toString().trim().isEmpty() && txtcustid.getText().trim().isEmpty() && txtqty.getText().trim().isEmpty() && txtprice.getText().trim().isEmpty() && txtempid.getText().trim().isEmpty()) {
            txtentoid.setText("Enter  Order ID");
            txtentcomboitemname.setToolTipText("Enter Item Name");
            txtentitemid.setText("Enter Item ID");
            txtentcustname.setText("Enter Customer Name");
            txtentcustid.setText("Enter Customer ID");
            txtentqty.setText("Enter Quantity");
            txtentprice.setText("Enter Price");

            txtentempid.setText("Enter Emp ID");
        } else if (txtoid.getText().trim().isEmpty()) {
            txtentoid.setText("Enter  Order ID");
        } else if (ComboItemName.getSelectedItem().toString().trim().isEmpty()) {
            txtentcomboitemname.setText("Enter Item Name");
        } else if (txtitemid.getText().trim().isEmpty()) {
            txtentitemid.setText("Enter Item ID");
        } else if (ComboCustName.getSelectedItem().toString().trim().isEmpty()) {
            txtentcustname.setText("Enter Customer Name");
        } else if (txtcustid.getText().trim().isEmpty()) {
            txtentcustid.setText("Enter Customer ID");
        } else if (txtqty.getText().trim().isEmpty()) {
            txtentqty.setText("Enter Quantity");
        } else if (txtprice.getText().trim().isEmpty()) {
            txtentprice.setText("Enter Price");

        } else if (txtempid.getText().trim().isEmpty()) {
            txtentempid.setText("Enter Emp ID");
        } else {  //is  this code kk
            try {
                if (Command == UPDATE) {
                    String sql = "update orders set  OrderID=?,"
                            + "ItemName=?,ItemID=?,CustName=?,CustID=?,Quantity=?,"
                            + "Price=?,TotalAmt=?,EmpID=? "
                            + "where  OrderID=?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, txtoid.getText());
                    pst.setString(2, ComboItemName.getSelectedItem().toString());
                    pst.setString(3, txtitemid.getText());
                    pst.setString(4, ComboCustName.getSelectedItem().toString());
                    pst.setString(5, txtcustid.getText());
                    pst.setString(6, txtqty.getText());
                    pst.setString(7, txtprice.getText());
                    // pst.setString(8,txtsub.getText());
                    pst.setString(8, txttotalamt.getText());
                    pst.setString(9, txtempid.getText());
                    pst.setString(10, txtoid.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "updated successfuly");
                    txtoid.setText("");
                    ComboItemName.setToolTipText("");
                    txtitemid.setText("");
                    ComboCustName.setToolTipText("");
                    txtcustid.setText("");
                    txtqty.setText("");
                    txtprice.setText("");
                    txttotalamt.setEnabled(false);
                    txttotalamt.setText("");
                    txtempid.setText("");
                    btndelete.setVisible(true);
                btnsearch.setVisible(true);
                btnsave.setVisible(true);
                btnupdate.setVisible(true);
                btnadd.setVisible(true);
                } else if (Command == ADD) {
                    // String sql = "Insert into orders (OrderID,ItemName,ItemID,CustName,CustID,Quantity,Price,TotalAmt,EmpID) values (?,?,?,?,?,?,?,?,?)";
                    String query = "{call AddOrder(?,?,?,?,?,?,?,?,?)}";
                    cs = conn.prepareCall(query);
                    cs.setInt(1, Integer.parseInt(txtoid.getText()));
                    cs.setString(2, ComboItemName.getSelectedItem().toString());
                    //cs.setInt(3, Integer.parseInt(txtitemid.getText()));
                    cs.setString(3, txtitemid.getText());
                    cs.setString(4, ComboCustName.getSelectedItem().toString());
                    cs.setString(5, txtcustid.getText());
                    // cs.setInt(5, Integer.parseInt(txtcustid.getText()));
                    cs.setString(6, txtqty.getText());
                    //  cs.setInt(6, Integer.parseInt(txtqty.getText()));
                    cs.setString(7, txtprice.getText());
                    // cs.setInt(7, Integer.parseInt(txtprice.getText()));

                    System.out.println("EMPID: " + txtempid.getText());
                    cs.setInt(9, Integer.parseInt(txtempid.getText()));
                    // cs.setString(9, txtempid.getText());

                    // pst.setString(8, txttotalamt.getText());
                    cs.registerOutParameter(8, java.sql.Types.INTEGER);

                    // cs.executeUpdate();
                    cs.executeUpdate();

                    int oParamData = cs.getInt(8);
                    txttotalamt.setText(oParamData + "");
                    //JOptionPane.showMessageDialog(null, "inserted successfully");
                    PreparedStatement pst1 ;
                            
                    String sql = "INSERT into printbill(OrderID,ItemName,ItemID,CustName,CustID,Quantity,Price,TotalAmt,EmpID)"
                            + "values (?,?,?,?,?,?,?,?,?);";
                    pst1 = conn.prepareStatement(sql);

                    pst1.setInt(1, Integer.parseInt(txtoid.getText()));
                    pst1.setString(2, ComboItemName.getSelectedItem().toString());
                    //cs.setInt(3, Integer.parseInt(txtitemid.getText()));
                    pst1.setString(3, txtitemid.getText());
                    pst1.setString(4, ComboCustName.getSelectedItem().toString());
                    pst1.setString(5, txtcustid.getText());
                    // cs.setInt(5, Integer.parseInt(txtcustid.getText()));
                    pst1.setString(6, txtqty.getText());
                    //  cs.setInt(6, Integer.parseInt(txtqty.getText()));
                    pst1.setString(7, txtprice.getText());
                    // cs.setInt(7, Integer.parseInt(txtprice.getText()));

                    pst1.setInt(8, oParamData);
                    pst1.setInt(9, Integer.parseInt(txtempid.getText()));

                    pst1.executeUpdate();
                    String IDUpdateQry = "Update autogen SET OrderID=?";

                    pst = conn.prepareStatement(IDUpdateQry);
                    pst.setString(1, "" + (Integer.parseInt(txtoid.getText()) + (int) 1));
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "inserted successfully\nTotal Amount=" + oParamData);

                    btndelete.setVisible(true);
                    btnsearch.setVisible(true);
                    btnsave.setVisible(true);
                    btnupdate.setVisible(true);
                    btnadd.setVisible(true);
                    txtoid.setText("");
                    ComboItemName.setToolTipText("");
                    txtitemid.setText("");
                    ComboCustName.setToolTipText("");
                    txtcustid.setText("");
                    txtqty.setText("");
                    txtprice.setText("");
                    txttotalamt.setEnabled(false);
                    txttotalamt.setText("");
                    txtempid.setText("");

                }
                txtitemid.setEnabled(false);
                ComboCustName.setEnabled(false);
                txtcustid.setEnabled(false);
                txtqty.setEnabled(false);
                txtprice.setEnabled(false);
                txttotalamt.setEnabled(false);
                txtempid.setEnabled(false);

            } catch (Exception ex) {
                Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        try {

            txtitemid.setEnabled(true);
            ComboCustName.setEnabled(true);
            txtcustid.setEnabled(true);
            txtqty.setEnabled(true);
            txtprice.setEnabled(true);
            txttotalamt.setEnabled(true);
            txtempid.setEnabled(true);
            Command = UPDATE;
            
              String sql2 = "SELECT * FROM `orders` WHERE OrderID ='"+txtoid.getText()+"';";
            pst = conn.prepareStatement(sql2);
            //pst.setString(1, ComboCustName.getSelectedItem().toString());
          
            rs = pst.executeQuery();
            if (rs.next()) {
                //txtoid.setText(rs.getString("OrderID"));
                
                ComboItemName.setSelectedItem(rs.getString("ItemName"));
                txtitemid.setText(rs.getString("ItemID"));
                ComboCustName.setSelectedItem(rs.getString("CustName"));
                txtcustid.setText(rs.getString("CustID"));
                txtqty.setText(rs.getString("Quantity"));
                txtprice.setText(rs.getString("Price"));
                txttotalamt.setText(rs.getString("TotalAmt"));
                txtempid.setText(rs.getString("EmpID"));
                

            } else {
                JOptionPane.showMessageDialog(null, "incorrect OrderID");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txttotalamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalamtActionPerformed

    }//GEN-LAST:event_txttotalamtActionPerformed

    private void txtcustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustidActionPerformed

    private void txtitemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemidActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        txtoid.setText("");
        ComboItemName.setToolTipText("");
        txtitemid.setText("");
        ComboCustName.setToolTipText("");
        txtcustid.setText("");
        txtqty.setText("");
        txtprice.setText("");
        txttotalamt.setText("");
        txtempid.setText("");

        txtitemid.setEnabled(true);
        ComboCustName.setEnabled(true);
        txtcustid.setEnabled(true);
        txtqty.setEnabled(true);
        txtprice.setEnabled(true);
        txttotalamt.setEnabled(false);
        txtempid.setEnabled(true);
        
        btnupdate.setVisible(true);
        btnadd.setVisible(true);
        btnsave.setVisible(true);
        btnsearch.setVisible(true);
        btndelete.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempidActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        URL resource =getClass().getResource("/iconandpictures/ordersback1.jpg");

        try {
            //System.out.println(Paths.get(resource.toURI()).toFile().getAbsolutePath());
            imagePanel1.setImage(new ImageIcon(resource).getImage(),
                    this.getWidth(), this.getHeight());
        } catch (Exception ex) {
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentResized

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void ComboCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCustNameActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void ComboItemNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboItemNameItemStateChanged
        try {
            Connection connL;
            connL = dbconnect.connectdb();
            ResultSet rsL;
            PreparedStatement pstL;
            String SelectedItem = ComboItemName.getSelectedItem().toString();
            String Qry = "select ItemID from item where ItemName = '" + SelectedItem + "';";

            pstL = connL.prepareStatement(Qry);
            rsL = pstL.executeQuery();
            if (rsL.next()) {
                txtitemid.setText(rsL.getString("ItemID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboItemNameItemStateChanged

    private void ComboCustNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCustNameItemStateChanged
        try {
            Connection connL;
            connL = dbconnect.connectdb();
            ResultSet rsL;
            PreparedStatement pstL;
            String SelectedItem = ComboCustName.getSelectedItem().toString();
            String Qry = "SELECT CustID from customer where CustName = '" + SelectedItem + "';";

            pstL = connL.prepareStatement(Qry);
            rsL = pstL.executeQuery();
            if (rsL.next()) {
                txtcustid.setText(rsL.getString("CustID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboCustNameItemStateChanged

    private void txtoidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoidKeyTyped
      txtentoid.setText("");
    }//GEN-LAST:event_txtoidKeyTyped

    private void ComboItemNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboItemNameKeyTyped
       txtentcomboitemname.setText("");
    }//GEN-LAST:event_ComboItemNameKeyTyped

    private void txtitemidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemidKeyTyped
       txtentitemid.setText("");
    }//GEN-LAST:event_txtitemidKeyTyped

    private void ComboCustNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboCustNameKeyTyped
        txtentcustname.setText("");
    }//GEN-LAST:event_ComboCustNameKeyTyped

    private void txtcustidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustidKeyTyped
       txtentcustid.setText("");
    }//GEN-LAST:event_txtcustidKeyTyped

    private void txtqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyTyped
        txtentqty.setText("");
    }//GEN-LAST:event_txtqtyKeyTyped

    private void txtpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyTyped
      txtentprice.setText("");
    }//GEN-LAST:event_txtpriceKeyTyped

    private void txttotalamtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalamtKeyTyped
       txtenttotalamt.setText("");
    }//GEN-LAST:event_txttotalamtKeyTyped

    private void txtempidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtempidKeyTyped
       txtentempid.setText("");
    }//GEN-LAST:event_txtempidKeyTyped

    private void txttotalamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalamtKeyPressed
        String qty = txtqty.getText();
        Double qty1 = Double.parseDouble(qty);
        String price = txtprice.getText();
        Double price1 = Double.parseDouble(price); 
        Double total=qty1*price1;
        txttotalamt.setText("" + total);

// TODO add your handling code here:
    }//GEN-LAST:event_txttotalamtKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Order().setVisible(true);
//            }
//        });
  //S  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCustName;
    private javax.swing.JComboBox<String> ComboItemName;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private coffee.ImagePanel imagePanel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtempid;
    private javax.swing.JLabel txtentcomboitemname;
    private javax.swing.JLabel txtentcustid;
    private javax.swing.JLabel txtentcustname;
    private javax.swing.JLabel txtentempid;
    private javax.swing.JLabel txtentitemid;
    private javax.swing.JLabel txtentoid;
    private javax.swing.JLabel txtentprice;
    private javax.swing.JLabel txtentqty;
    private javax.swing.JLabel txtenttotalamt;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JTextField txtoid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txttotalamt;
    // End of variables declaration//GEN-END:variables
}
